### ISSUE TITLE
Unnecessary fmod in Is Prime/is_prime.c

### ISSUE THREAD

**Issue by KasperJSdeVries** [Muffinrl/C-assignments#1]
on line 36 of "Is Prime/is_prime.c" it uses fmod where a "%" operator would suffice as it is only operating on integers.

**Comment by Muffinrl** [comment]
> on line 36 of "Is Prime/is_prime.c" it uses fmod where a "%" operator would suffice as it is only operating on integers.

resolved, thank you for the feedback :)

**Comment by KasperJSdeVries** [comment]
The Same issue is present in the Primes exercise

**Comment by Muffinrl** [comment]
fixed :)
